name: dictionary_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.3
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.1
  url_launcher: ^6.2.6 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Regular.ttf
        - asset: assets/fonts/Avenir-Italic.otf
          style: italic
        - asset: assets/fonts/Avenir-Bold.ttf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#EFEBE0"
  color_dark: "#262626"
  image: assets/icon/icon_2.png
  android_12:
    image: assets/icon/icon_2.png
    color: "#EFEBE0"
    color_dark: "#262626"
